<<<<<<< HEAD
[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python3 run.py"
=======
[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "/opt/venv/bin/python run.py"
>>>>>>> 5dd15dffff001b74734abc4686920d85ea5cfbb3
